### ISSUE TITLE
Resource type [service] is not creatable

### ISSUE THREAD

**Issue by ynott** [kenfdev/faas-rancher#1]
@kenfdev 
Thank you for your  great catalog on rancher.

I had a try to do simple test on my rancher enviroment. 
(Follow this blog.)
https://medium.com/cloud-academy-inc/openfaas-on-rancher-684650cc078e

But I can't creat a new function on OpenFaaS Portal UI.

In my browser console said , "VM255:1 POST http://xxxxxx:8081/system/functions 500 (Internal Server Error)" ,
then I saw a container log on openfaas/faas-rancher,
It was showed below log.

```
2017/10/13 10:19:24Created Rancher Client
2017/10/13 10:25:162017/10/13 01:25:16 Resource type [service] is not creatable
2017/10/13 10:25:562017/10/13 01:25:56 Resource type [service] is not creatable
2017/10/13 10:29:562017/10/13 01:29:56 Resource type [service] is not creatable
2017/10/13 10:31:432017/10/13 01:31:43 Resource type [service] is not creatable
```

Do you have anything advices to me?

**Comment by ynott** [comment]
Sorry. 😢 
This is my fault.
I made a API Key in "Account API Key".

I try to remake the stack  with the "Environment API Key" in the next time,
This problem is resolved.

Thanks for your advice. 👍

**Comment by kenfdev** [comment]
@ynott Thanks a lot for trying `faas-rancher` . These feedbacks really mean a lot!
Yes, it is quite confusing but `Account API Key`s aren't supported for now. You'll have to create `Environment API Key`s
